defaults:
  - _self_
  - dataset: dataset
  - model: mlp
  - scheduler: warmup_cosine
  - exp: source_train

# meta_path: "data"
meta_path: "data_55"
seed: 42

result_root: "experiment_result"
weight_root: "model_weight"
log_root: "logs"